# Determinant of a matrix using function recursion

In [1]:
import numpy as np

def determinant(matrix,n):
    if n==1:                                               #base case for 1x1 matrix
        return matrix[0,0]                             
    if n==2:                                               #base case 2x2 matrix
        return matrix[0,0]*matrix[1,1]-matrix[0,1]*matrix[1,0]
    
    det=0
    reduced_matrix=matrix[1:,:]                            #remove the first row
    for j in range(n):
        submatrix=np.concatenate((reduced_matrix[:,:j],reduced_matrix[:,j+1:]),axis=1)        #create submatrix by excluding the j-th column using 2D array slicing and joining left and right side of jth column
        det+=((-1)**j)*matrix[0,j]*determinant(submatrix,n-1)                                 #laplace expansion formula
    
    return det

n=4
A=np.random.randint(1,10,size=(n,n))
print("Matrix A is :")
print()
print(A)
print()

print('The determinant of the matrix is :',determinant(A,n))

Matrix A is :

[[6 2 1 5]
 [2 7 5 5]
 [7 3 5 6]
 [9 7 8 2]]

The determinant of the matrix is : -941


# Solution of linear simultaneous equation using Gauss Elimination Method
Without Pivot Check

In [2]:
import numpy as np

#Create the augmented matrix
def get_mat(n,m):
    print('Enter the elements of augmented matrix : ')
    M=np.empty((n,m))
    for i in range(n):
        for j in range(m):
            M[i][j]=eval(input())
    return M

#Print the augmented matrix
def show_mat(M):
    for i in M:
        for j in i:
            print(format(j,'0.3f'),end=' ')
        print()

#Call input augmented matrix function of size (n)*(n+1)  
n=int(input('Enter the number of system of linear equations :'))
m=n+1
AB=get_mat(n,m)
print()

#Print the augmented matrix
print('The augmented matrix is :')
show_mat(AB)
print()

#Create the coefficient matrix of size n*n
A=AB[:,0:n]

if np.linalg.det(A)!=0:
    print('Solution for given set of equation is consistent')
    print()
    for k in range(0,n-1):                      #controls the repeated operations on updated matrix
        for i in range(k+1,n):                  #controls row   
            ratio=AB[i][k]/AB[k][k]
            for j in range(0,n+1):              #controls column
                AB[i][j]-=AB[k][j]*ratio
    
    #Print the reduced augmented matrix
    print('The reduced augmented matrix is : ')
    show_mat(AB)
    print()
    
    #Back Substitution
    X=np.empty(n)                #Solution Matrix
    for i in range(n-1,-1,-1):   #Begins from n-1 th index, ends at index before -1 i.e 0
        X[i]=AB[i][n]            #Reduced constant matrix
        for j in range(i+1,n):
            X[i]-=AB[i][j]*X[j]
        X[i]=X[i]/AB[i][i]
    print('The solutions are : ',X)
    
else:
    print('The system of equations are inconsistent')

Enter the number of system of linear equations : 3


Enter the elements of augmented matrix : 


 2
 1
 4
 3
 2
 6
 9
 4
 7
 2
 1
 4



The augmented matrix is :
2.000 1.000 4.000 3.000 
2.000 6.000 9.000 4.000 
7.000 2.000 1.000 4.000 

Solution for given set of equation is consistent

The reduced augmented matrix is : 
2.000 1.000 4.000 3.000 
0.000 5.000 5.000 1.000 
0.000 0.000 -11.500 -6.200 

The solutions are :  [ 0.59130435 -0.33913043  0.53913043]


# Solution of linear simultaneous equation using Gauss Elimination Method
With Initial Pivot Check (Semi partial pivoting : Doesn't searches for largest element while swapping)

In [5]:
import numpy as np

#Create the augmented matrix
def get_mat(n,m):
    print('Enter the elements of augmented matrix : ')
    M=np.empty((n,m))
    for i in range(n):
        for j in range(m):
            M[i][j]=eval(input())
    return M

#Print the augmented matrix
def show_mat(M):
    for i in M:
        for j in i:
            print(format(j,'0.3f'),end=' ')
        print()

#Call input augmented matrix function of size (n)*(n+1)  
n=int(input('Enter the number of system of linear equations : '))
m=n+1
AB=get_mat(n,m)
print()

#Print the augmented matrix
print('The augmented matrix is :')
show_mat(AB)
print()

#Check and perform row swap if zeros found in the diagonal elements i.e pivot points
def mat_check(M):
    for p in range(0,n):
        for t in range(p+1,n):               #looks for rows below pivot row to prevent modifying previous pivot row
            if M[p][p]==0 and M[t][p]!=0:    #Checks for zero in diagonal position and searches a non zero element in the same column and swaps the rows if found
                M[[p,t],:]=M[[t,p],:]        #This is equivalent of : temp = AB[p,:].copy(), AB[p,:]=AB[t,:], AB[t,:]=temp
    return M

AB=mat_check(AB)
print('The augmented matrix with necessary swapping is :')
show_mat(AB)
print()

#Create the coefficient matrix of size n*n
A=AB[:,0:n]

flag=True
if np.linalg.det(A)!=0:
    print('Solution for given set of equation is consistent')
    print()
    for k in range(0,n-1):
        if AB[k][k]==0:                 #Exits Gaussian Elimination if the initial row swap doesnt' occurs
            flag=False
            break           
        else:
            for i in range(k+1,n):
                if AB[i][k]==0:         #Skips a row iteration if the element below pivot is already zero
                    continue
                ratio=AB[i][k]/AB[k][k] 
                AB[i,:]-=AB[k,:]*ratio  #Iterates over all column at once using vectorization
   
   #Print the reduced augmented matrix
    print('The reduced augmented matrix is : ')
    show_mat(AB)
    print()
    
    #Back Substitution
    if flag==True:
        X=np.empty(n)                #Solution Matrix
        for i in range(n-1,-1,-1):   #Begins from n-1 th index, ends at index before -1 i.e 0
            X[i]=AB[i][n]            #Reduced constant matrix
            for j in range(i+1,n):
                X[i]-=AB[i][j]*X[j]
            X[i]=X[i]/AB[i][i]
        print('The solutions are : ',X)
    else:
        print('Gauss elimination Method is not applicable') #pivot is zero
else:
    print('The system of equations is inconsistent')

Enter the number of system of linear equations :  4


Enter the elements of augmented matrix : 


 0
 0
 3
 4
 2
 2
 0
 3
 2
 5
 2
 6
 0
 4
 9
 2
 0
 4
 3
 6



The augmented matrix is :
0.000 0.000 3.000 4.000 2.000 
2.000 0.000 3.000 2.000 5.000 
2.000 6.000 0.000 4.000 9.000 
2.000 0.000 4.000 3.000 6.000 

The augmented matrix with necessary swapping is :
2.000 0.000 3.000 2.000 5.000 
2.000 6.000 0.000 4.000 9.000 
0.000 0.000 3.000 4.000 2.000 
2.000 0.000 4.000 3.000 6.000 

Solution for given set of equation is consistent

The reduced augmented matrix is : 
2.000 0.000 3.000 2.000 5.000 
0.000 6.000 -3.000 2.000 4.000 
0.000 0.000 3.000 4.000 2.000 
0.000 0.000 0.000 -0.333 0.333 

The solutions are :  [ 0.5  2.   2.  -1. ]


# Solution of linear simultaneous equation using Gauss Elimination Method
With Initial Partial Pivoting Check 

In [1]:
import numpy as np

#Create the augmented matrix
def get_mat(n,m):
    print('Enter the elements of augmented matrix : ')
    M=np.empty((n,m))
    for i in range(n):
        for j in range(m):
            M[i][j]=eval(input())
    return M

#Print the augmented matrix
def show_mat(M):
    for i in M:
        for j in i:
            print(format(j,'0.3f'),end=' ')
        print()

#Call input augmented matrix function of size (n)*(n+1)  
n=int(input('Enter the number of system of linear equations : '))
m=n+1
AB=get_mat(n,m)
print()

#Print the augmented matrix
print('The augmented matrix is :')
show_mat(AB)
print()

#Swap pivot row with the row containing maximum absolute value of element in same column 
def mat_check(M):
    for p in range(n):
        max_index=p+np.argmax(np.abs(M[p:,p]))   #returns the index of row below pivot row whose element is bigger than the pivot row in the actual matrix
        if max_index!=p:
            M[[p,max_index],:]=M[[max_index,p],:]
    return M

AB=mat_check(AB)
print('The augmented matrix with necessary swapping is :')
show_mat(AB)
print()

#Create the coefficient matrix of size n*n
A=AB[:,0:n]

flag=True
if np.linalg.det(A)!=0:
    print('Solution for given set of equation is consistent')
    print()
    for k in range(0,n-1):
        if AB[k][k]==0:                 #Exits Gaussian Elimination if the initial row swap doesnt' occurs
            flag=False
            break           
        else:
            for i in range(k+1,n):
                if AB[i][k]==0:         #Skips a row iteration if the element below pivot is already zero
                    continue
                ratio=AB[i][k]/AB[k][k] 
                AB[i,:]-=AB[k,:]*ratio  #Iterates over all column at once using vectorization
   
   #Print the reduced augmented matrix
    print('The reduced augmented matrix is : ')
    show_mat(AB)
    print()
    
    #Back Substitution
    if flag==True:
        X=np.empty(n)                #Solution Matrix
        for i in range(n-1,-1,-1):   #Begins from n-1 th index, ends at index before -1 i.e 0
            X[i]=AB[i][n]            #Reduced constant matrix
            for j in range(i+1,n):
                X[i]-=AB[i][j]*X[j]
            X[i]=X[i]/AB[i][i]
        print('The solutions are : ',X)
    else:
        print('Gauss elimination Method is not applicable') #pivot is zero
else:
    print('The system of equations is inconsistent')

Enter the number of system of linear equations :  4


Enter the elements of augmented matrix : 


 0
 0
 3
 4
 2
 2
 0
 3
 2
 5
 2
 6
 0
 4
 9
 2
 0
 4
 3
 6



The augmented matrix is :
0.000 0.000 3.000 4.000 2.000 
2.000 0.000 3.000 2.000 5.000 
2.000 6.000 0.000 4.000 9.000 
2.000 0.000 4.000 3.000 6.000 

The augmented matrix with necessary swapping is :
2.000 0.000 3.000 2.000 5.000 
2.000 6.000 0.000 4.000 9.000 
2.000 0.000 4.000 3.000 6.000 
0.000 0.000 3.000 4.000 2.000 

Solution for given set of equation is consistent

The reduced augmented matrix is : 
2.000 0.000 3.000 2.000 5.000 
0.000 6.000 -3.000 2.000 4.000 
0.000 0.000 1.000 1.000 1.000 
0.000 0.000 0.000 1.000 -1.000 

The solutions are :  [ 0.5  2.   2.  -1. ]


# Solution of linear simultaneous equation using Gauss Elimination Method
With Partial Pivoting Check during reduction 

In [2]:
import numpy as np

#Create the augmented matrix
def get_mat(n,m):
    print('Enter the elements of augmented matrix : ')
    M=np.empty((n,m))
    for i in range(n):
        for j in range(m):
            M[i][j]=eval(input())
    return M

#Print the augmented matrix
def show_mat(M):
    for i in M:
        for j in i:
            print(format(j,'0.3f'),end=' ')
        print()

#Call input augmented matrix function of size (n)*(n+1)  
n=int(input('Enter the number of system of linear equations : '))
m=n+1
AB=get_mat(n,m)
print()

#Print the augmented matrix
print('The augmented matrix is :')
show_mat(AB)
print()

#Swap pivot row with the row containing maximum absolute value of element in same column 
def mat_check(M,start_index):
    for p in range(start_index,n):
        max_index=p+np.argmax(np.abs(M[p:,p]))   #returns the index of row below pivot row whose element is bigger than the pivot row in the actual matrix
        if max_index!=p:
            M[[p,max_index],:]=M[[max_index,p],:]
    return M

#Create the coefficient matrix of size n*n
A=AB[:,0:n]

flag=True
if np.linalg.det(A)!=0:
    print('Solution for given set of equation is consistent')
    print()
    for k in range(0,n-1):
        AB=mat_check(AB,k)
        if AB[k][k]==0:                 #Exits Gaussian Elimination if the initial row swap doesnt' occurs
            flag=False
            break           
        else:
            for i in range(k+1,n):
                if AB[i][k]==0:         #Skips a row iteration if the element below pivot is already zero
                    continue
                ratio=AB[i][k]/AB[k][k] 
                AB[i,:]-=AB[k,:]*ratio  #Iterates over all column at once using vectorization
   
   #Print the reduced augmented matrix
    print('The reduced augmented matrix is : ')
    show_mat(AB)
    print()
    
    #Back Substitution
    if flag==True:
        X=np.empty(n)                #Solution Matrix
        for i in range(n-1,-1,-1):   #Begins from n-1 th index, ends at index before -1 i.e 0
            X[i]=AB[i][n]            #Reduced constant matrix
            for j in range(i+1,n):
                X[i]-=AB[i][j]*X[j]
            X[i]=X[i]/AB[i][i]
        print('The solutions are : ',X)
    else:
        print('Gauss elimination Method is not applicable') #pivot is zero
else:
    print('The system of equations is inconsistent')

Enter the number of system of linear equations :  4


Enter the elements of augmented matrix : 


 1
 2
 3
 4
 10
 0
 0
 1
 1
 0
 0
 -1
 -2
 -3
 -5
 0
 -1
 -7
 -6
 -18



The augmented matrix is :
1.000 2.000 3.000 4.000 10.000 
0.000 0.000 1.000 1.000 0.000 
0.000 -1.000 -2.000 -3.000 -5.000 
0.000 -1.000 -7.000 -6.000 -18.000 

Solution for given set of equation is consistent

The reduced augmented matrix is : 
1.000 2.000 3.000 4.000 10.000 
0.000 -1.000 -2.000 -3.000 -5.000 
0.000 0.000 -5.000 -3.000 -13.000 
0.000 0.000 0.000 0.400 -2.600 

The solutions are :  [-6.5 11.5  6.5 -6.5]


# Solution of linear simultaneous equation using solve() function of linalg submodule of numpy

In [9]:
import numpy as np 

n=int(input('Enter no. of unknowns : '))
A=np.empty((n,n))
B=np.empty(n)

print('Enter elements of co-efficient matrix : ')
for i in range(n):
    for j in range(n):
        A[i][j]=eval(input())

print('Enter RHS Constant Matrix :')
for i in range(n):
    B[i]=eval(input())

X=np.linalg.solve(A,B)
print('The solutions are :',X)

Enter no. of unknowns :  3


Enter elements of co-efficient matrix : 


 4
 5
 3
 2
 1
 6
 6
 7
 5


Enter RHS Constant Matrix :


 9
 8
 7


The solutions are : [-29.33333333  20.66666667   7.66666667]


# Matrix Multiplication using array

In [ ]:
import numpy as np  
def get_mat(m,n):                         #Taking inputs in matrix form one by one
    print('Enter elements of matrix :')
    M=np.empty((m,n))
    for i in range(m):
        for j in range(n):
            M[i][j]=eval(input())
    return M

def show_mat(M,m,n):                     #Printing the array in matrix form   
    for i in M:
        for j in i:
            print(j,end=' ')
        print()

def mat_prod(A1,A2,m,p,n):
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            for k in range(p):
                C[i][j]+=A1[i][k]*A2[k][j]
    return C

r1=eval(input('Enter row size of 1st matrix : '))
c1=eval(input('Enter column size of 1st matrix : '))
M1=get_mat(r1,c1)
print('The 1st matrix is :')
show_mat(M1,r1,c1)

r2=eval(input('Enter row size of 2nd matrix : '))
c2=eval(input('Enter column size of 2nd matrix : '))
M2=get_mat(r2,c2)
print('The 2nd matrix is: ')
show_mat(M2,r2,c2)

if c1==r2:
    M3=mat_prod(M1,M2,r1,c1,c2)
    print('Resultant matrix is :')
    show_mat(M3,r2,c1)
else:
    print('Matrix multiplication is not possible')

# Matrix addition using array

In [3]:
import numpy as np  
def get_mat(m,n):                         #Taking inputs in matrix form one by one
    print('Enter elements of matrix : ')
    M=np.empty((m,n))
    for i in range(m):
        for j in range(n):
            M[i][j]=eval(input())
    return M

def show_mat(M,m,n):                      #Printing the array in matrix form    
    for i in M:
        for j in i:
            print(j,end=' ')
        print()

def mat_sum(A1,A2,m,n):
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i][j]+=A1[i][j]*A2[i][j]
    return C

r1=eval(input('Enter row size of 1st matrix : '))
c1=eval(input('Enter column size of 1st matrix : '))
M1=get_mat(r1,c1)
print('The 1st matrix is :')
show_mat(M1,r1,c1)

r2=eval(input('Enter row size of 2nd matrix : '))
c2=eval(input('Enter column size of 2nd matrix : '))
M2=get_mat(r2,c2)
print('The 2nd matrix is :')
show_mat(M2,r2,c2)

if c1==c2 and r1==r2:
    M3=mat_sum(M1,M2,r1,c1)
    print('Resultant matrix is :')
    show_mat(M3,r1,c1)
else:
    print('Matrix adition is not possible')

Enter row size of 1st matrix :  2
Enter column size of 1st matrix :  3


Enter elements of matrix : 


 1
 8
 7
 3
 6
 5


The 1st matrix is :
1.0 8.0 7.0 
3.0 6.0 5.0 


Enter row size of 2nd matrix :  2
Enter column size of 2nd matrix :  3


Enter elements of matrix : 


 5
 7
 9
 3
 2
 5


The 2nd matrix is :
5.0 7.0 9.0 
3.0 2.0 5.0 
Resultant matrix is :
5.0 56.0 63.0 
9.0 12.0 25.0 


# Matrix Transpose using array

In [5]:
import numpy as np
def get_mat(m,n):                         #Taking inputs in matrix form one by one
    print('Enter elements of matrix :')
    A=np.empty((m,n))
    for i in range(m):
        for j in range(n):
            A[i][j]=eval(input())
    return A

def show_mat(A):                          #Printing array in matrix form(note: The other print method is inapplicable here)
    for i in A:
        for j in i:
            print(j,end=' ')
        print()
        
#for any size matrix
def transpose(A,m,n):
    B=np.empty((n,m))
    for i in range(n):
        for j in range(m):
            B[i][j]=A[j][i]
    return B

m=int(input('Enter row size : '))
n=int(input('Enter column size : '))
A=get_mat(m,n)

print()
print('The input matrix is :')
show_mat(A)

print()
TM=transpose(A,m,n)
print('The matrix after transpose is :')
show_mat(TM)

Enter row size :  3
Enter column size :  3


Enter elements of matrix :


 1
 2
 5
 9
 8
 6
 2
 4
 3



The input matrix is :
1.0 2.0 5.0 
9.0 8.0 6.0 
2.0 4.0 3.0 

The matrix after transpose is :
1.0 9.0 2.0 
2.0 8.0 4.0 
5.0 6.0 3.0 


# Diagonalizaton of matrix using linalg submodule of numpy and finding eigenvalues,eigenvectors

In [6]:
import numpy as np
A=np.array([[2,0,0],[1,2,1],[-1,0,1]])
print('The given matrix is :')
print(A)
print()

eigval,eigvec=np.linalg.eig(A)

print('The eigenvalues are :', eigval)
print()
print('The eigenvectors are :')

for i in range(len(eigvec)):
    print(eigvec[:,i])

print()   
A_Diag=np.dot(np.dot(np.linalg.inv(eigvec),A),eigvec)    #using PAP^(-1)
print('The diagonal matrix of given matrix is :')
print(A_Diag)

The given matrix is :
[[ 2  0  0]
 [ 1  2  1]
 [-1  0  1]]

The eigenvalues are : [2. 1. 2.]

The eigenvectors are :
[0. 1. 0.]
[ 0.         -0.70710678  0.70710678]
[ 0.70710678  0.         -0.70710678]

The diagonal matrix of given matrix is :
[[2.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.02930727e-17]
 [0.00000000e+00 0.00000000e+00 2.00000000e+00]]


# Diagonalization of matrix using sympy module 

In [7]:
from sympy import *  #import statement that imports all functions, classes and variables from the sympy module 
import numpy as np
M=[[1,2,3],[4,5,6],[7,8,9]]
M1=Matrix(M)         #change to matrix object
P,D=M1.diagonalize()
print(D)

Matrix([[0, 0, 0], [0, 15/2 - 3*sqrt(33)/2, 0], [0, 0, 15/2 + 3*sqrt(33)/2]])
