# 1D Array Creation
Array is a structure and its corresponding variables/objects store same type of object/data in consecutive memory location. Array is 1-dimensional or multi-dimensional

In [2]:
import numpy as np
L=np.arange(1,10,0.5)
print(L)        #Generates an array of one dimension with numbers between 1 to 10 with step length 0.5

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [39]:
L=np.arange(1,10,1) 
print(L)        #Generates an array of one dimension with numbers between 1 to 10 with step length 1 and excludes last element

[1 2 3 4 5 6 7 8 9]


In [40]:
L=np.linspace(1,2,10)
print(L)           #Generates an equispaced array of one dimension with 10 numbers between 1 to 2 and includes the last number

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [41]:
L=np.linspace(1,10,10)
print(L)        #Generates an equispaced array of one dimension with 10 numbers between 1 to 10 and includes last number

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
L=np.linspace(5,16,10)
print(L)

[ 5.          6.22222222  7.44444444  8.66666667  9.88888889 11.11111111
 12.33333333 13.55555556 14.77777778 16.        ]


In [42]:
L=np.arange(5,16,1.2222222)  #step=(upper-lower)/(no of elelments-1)
print(L) 

[ 5.         6.2222222  7.4444444  8.6666666  9.8888888 11.111111
 12.3333332 13.5555554 14.7777776 15.9999998]


In [14]:
A=np.array([2,5,7,9])
print(A)        #Generates an array with the specified values

[2 5 7 9]


In [15]:
A=np.logspace(3,8,4,base=2)
print(A)        #Generates an 1D array with logarithmic value from 3 to 8 with base value 2

[  8.          25.39841683  80.63494719 256.        ]


In [16]:
A=np.zeros(4)
print(A)        #Generates an array of size 4 with all zeros

[0. 0. 0. 0.]


In [17]:
A=np.ones(4)
print(A)        #Generates an array of size 4 with all ones

[1. 1. 1. 1.]


# 2D Array Creation

In [71]:
A=np.array([[4,5,6],[7,8,9]])
print(A)

[[4 5 6]
 [7 8 9]]


In [48]:
B=np.empty((3,3),dtype=int)   #By default,reads float
print(B)        #Generates an 2D trash value array of size 3×3 and stores integer data type

[[   4128860    6029375    3801155]
 [   5570652    6619251    7536754]
 [1171456000        311    6815860]]


In [44]:
A=np.zeros((4,4))
print(A)        #Generates an array of 4×4 dimension with all zeroes

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
A=np.eye(3)
print(A)        #Generates an identity matrix of order 3×3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
B=np.eye(4)
B.fill(7)
print(B)        #Fills an array with values 7 by overwriting

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [50]:
A=np.full((2,3),2)
print(A)        #Fills an array with values 2 of 2×3 order

[[2 2 2]
 [2 2 2]]


# Editing an array

In [59]:
#Change dimension/shape
A=np.empty((2,3))
A.fill(3)
print('Original Array: \n',A)
A=A.reshape((3,2))                    #can add dtype if required
print('Reshaped Array: \n',A)         #Dimension of previously made array is changed

Original Array: 
 [[3. 3. 3.]
 [3. 3. 3.]]
Reshaped Array: 
 [[3. 3.]
 [3. 3.]
 [3. 3.]]


In [58]:
#Change any array to a 1D array
A=np.empty((2,3))
A.fill(3)
A=A.flatten()
print(A)              

[3. 3. 3. 3. 3. 3.]


In [57]:
#Combine two arrays vertcally
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
print(A,B)
C=np.vstack((A,B))
print(C)          

[1 2 3 4] [5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [60]:
#Combine two arrays horizontally
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
print(A,B)
C=np.hstack((A,B))
print(C)

[1 2 3 4] [5 6 7 8]
[1 2 3 4 5 6 7 8]


In [66]:
#Extract Diagonal Elements from 2D array
A=np.eye(4)
print(A)
C=np.diagonal(A)
print("The diagonal elements are :",C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The diagonal elements are : [1. 1. 1. 1.]


# Attributes of array

In [68]:
A=np.empty((3,3),dtype=int)
print(A)
Dimension=A.ndim
print('Dimension :',Dimension)
Size=A.size
print('Size :',Size)
Shape=A.shape
print('Shape :',Shape)
Type=A.dtype
print('Data type :',Type)
Itemsize=A.itemsize
print('Itemsize :',Itemsize)        #memory used by elements in bits

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension : 2
Size : 9
Shape : (3, 3)
Data type : int32
Itemsize : 4


In [69]:
A=np.eye(4)
Min=np.min(A)
Max=np.max(A)
Minindex=np.argmin(A)
Maxindex=np.argmax(A)
Mean=np.mean(A)
Median=np.median(A)
Var=np.var(A)
SD=np.std(A)


print('minimum element: ',Min)
print('maximum element: ',Max)
print('index of minimum element: ',Minindex)
print('index of maximum element: ',Maxindex)
print('mean of array elements: ',Mean)
print('median of array elements: ',Median)
print('variance of array elements: ',Var)
print('standard deviation of array elements: ',SD)

minimum element:  0.0
maximum element:  1.0
index of minimum element:  1
index of maximum element:  0
mean of array elements:  0.25
median of array elements:  0.0
variance of array elements:  0.1875
standard deviation of array elements:  0.4330127018922193


# Dot product of two 1D array as vectors
multiplies same length arrays pairwise and adds them

In [70]:
a=np.array([1,2,3,4])
b=np.array([3,5,7,9])
print(np.dot(a,b))

70


# Product of two 2D arrays as matrix
proper dimension required for the matrices

In [6]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,7],[2,1],[5,3]])
print(np.dot(a,b))

[[23 18]
 [67 62]]


In [8]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,7],[2,1],[5,3]])
print(a@b)

[[23 18]
 [67 62]]


In [9]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,7],[2,1],[5,3]])
print(np.matmul(a,b))

[[23 18]
 [67 62]]


# Scalar multiply element wise with an array

In [7]:
a=2
b=np.array([3,5,7,9])
print(np.dot(a,b))

[ 6 10 14 18]


In [10]:
a=2
b=np.array([[4,7],[2,1],[5,3]])
print(np.dot(a,b))

[[ 8 14]
 [ 4  2]
 [10  6]]


# Linear Algebra using array

In [74]:
#Determinant
a=np.array([[0, 1], [1,0]])
print(a)
determinant=np.linalg.det(a)
print(determinant)

[[0 1]
 [1 0]]
-1.0


In [80]:
#Eigenvalue and Eigenvector
a=np.array([[0, 1], [1,0]])
print(a)
eigenvalues,eigenvectors=np.linalg.eig(a)
eig=np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)     #prints a n/n array with each column denoting eigenvector
print()
print(eig)

[[0 1]
 [1 0]]
[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

EigResult(eigenvalues=array([ 1., -1.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [83]:
#Matrix Multiplication
A=np.array([[1,3],[2,4]])
B=np.array([[4,-2],[-3,1]])
C=np.array([[1,2],[2,1]])
print(A*B+2*C)              #A*B performs elementwise multiplication
print(np.dot(A,B)+2*C)      #dot product of two square matrix is matrix multiplication

[[ 6 -2]
 [-2  6]]
[[-3  5]
 [ 0  2]]


In [87]:
#Vectorization
from datetime import datetime
x=np.random.rand(10**8)
y=np.random.rand(10**8)
t1=datetime.now()
z=x*y
t2=datetime.now()
print("For vectorised case, time required =", t2-t1)

For vectorised case, time required = 0:00:00.572323


In [89]:
x=np.random.rand(10**8)
y=np.random.rand(10**8)
z=np.random.rand(10**8)
t1_loop = datetime.now()
for i in range(10**8):
    z[i]=x[i]*y[i]
t2_loop=datetime.now()
print("For manual elementwise multiplication, time required =", t2_loop-t1_loop)

For manual elementwise multiplication, time required = 0:01:21.163513


# Assigning variable to an another array

In [90]:
from numpy import copy
x=np.array([1,1])
y=copy(x)
x[0]=5
print(x,y)

[5 1] [1 1]


# Slicing in 1D Array

In [4]:
A=np.array([2,5,7,6,3,4])
print(A[0])
print(A[-1])
print(A[0:])
print(A[:2])
print(A[1:4])
print(A[1:4:2])    #start(include element of this index), stop(dont include element of this index), step
print(A[:])
print(A[::])
print(A[5:0:-1])   #slicing from end

2
4
[2 5 7 6 3 4]
[2 5]
[5 7 6]
[5 6]
[2 5 7 6 3 4]
[2 5 7 6 3 4]
[4 3 6 7 5]


# Slicing in 2D Array

In [12]:
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A[:])
print(A[1:3,:])     #extracts rows from start to stop-1 A[start:stop,:]
print(A[:,1:3])     #extracts columns from start to stop-1 A[start:stop,:]
print(A[1:3,1:3])   #create sub-matrix

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[4 5 6]
 [7 8 9]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[5 6]
 [8 9]]
